const userActionType = {
    SET_USER_NAME:'SET_USER_NAME',
    GET_USER_NAME:'GET_USER_NAME',
    NEXT_QUESTION: 'NEXT_QUESTION',
    PREVIOUS_QUESTION: 'PREVIOUS_QUESTION',
    SET_SELECTED_QUESTION_LIST: 'SET_SELECTED_QUESTION_LIST',
    QUESTION_START_TIMER : 'START_TIMER',
    QUESTION_STOP_TIMER: 'STOP_TIMER',
    SET_START :'SET_START',
    SET_END :'SET_END',
    RESET: 'RESET',
}

export default userActionType